apiVersion: apps/v1
kind: Deployment
metadata:
  name: deimos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deimos
  template:
    metadata:
      labels:
        app: deimos
    spec:
      serviceAccountName: myapp-serviceaccount
      containers:
      - name: deimos-container
        image: gladium08/deimos:n16
        envFrom:
        - secretRef:
            name: deimos-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "name" is the name of the ClusterRole
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/log"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["wgpolicyk8s.io"]
  resources: ["policyreports", "clusterpolicyreports"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: myapp-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: deimos-secret
type: Opaque
data:
  DISCORD_WEBHOOKURL: "aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvd2ViaG9va3MvMTEzMzg0OTcxMjQ4NzgyNTQ3OC91V1BiTGg4S21naU9wSGJmV3R2MUhVVHNUMUNOV3VIdVB1czkxMG1WWGQtUWVFcXVZa3Nadm56alFlYWI3TDFjclhkag=="

  
